# Generated by Django 4.0.4 on 2022-05-16 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50)),
                ('text', models.CharField(max_length=300)),
                ('qtype', models.IntegerField(choices=[(1, 'Social'), (2, 'Physical'), (3, 'Money')])),
            ],
        ),
    ]
