# Generated by Django 4.0.3 on 2022-06-12 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_lat_user_lon'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='streaks',
            field=models.IntegerField(default=0),
        ),
    ]
