# Generated by Django 4.0.3 on 2022-06-02 12:21

import activities.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, max_length=200)),
                ('location', models.CharField(max_length=40)),
                ('location_type', models.CharField(choices=[('indoor', 'indoor'), ('outdooor', 'outdoor'), ('any', 'any')], default='any', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('sunny', 'sunny'), ('cloudy', 'cloudy'), ('windy', 'windy'), ('rainy', 'rainy'), ('snowy', 'snowy'), ('any', 'any')], default='any', max_length=20)),
                ('activity_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activities.activity')),
            ],
        ),
        migrations.CreateModel(
            name='ActivityScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[(1, 'Social'), (2, 'Physical'), (3, 'Money')], default='', max_length=40)),
                ('score', models.IntegerField(validators=[activities.models.validate_score])),
                ('activity_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activities.activity')),
            ],
        ),
    ]
