# Generated by Django 4.0.3 on 2022-06-12 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='lat',
            field=models.DecimalField(decimal_places=5, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='activity',
            name='lon',
            field=models.DecimalField(decimal_places=5, default=0.0, max_digits=10),
        ),
    ]
